### ISSUE TITLE
pytocs does not work

### ISSUE THREAD

**Issue by ekleiman22** [uxmal/pytocs#102]
I compiled the solution and got **pytocs.exe** in "C:\Users\myuser\Documents\Visual Studio 2019\Projects\pytocs-master\src\Cli\bin\Debug\net5.0". Then I run
"C:\Users\myuser\Documents\Visual Studio 2019\Projects\pytocs-master\src\Cli\bin\Debug\net5.0\pytocs.exe" hello.py 
in the directory where hello.py  is found. The program did nothing. When I clicked Enter I got in the same command window:
public static class module_name {
}
That's all.

**Comment by uxmal** [comment]
Can you provide me with the .py file you attempted to translate?

**Comment by ekleiman22** [comment]
Thank you, the program really works. I'm sorry that I did not write about this.
