### ISSUE TITLE
Important app. specified parentheses in python get removed during C# generation 

### ISSUE THREAD

**Issue by BrunoGagnon-Eaton** [uxmal/pytocs#17]
Example:
Python:  ret = a - (b + c)
C#: var ret = a - b + c;
C# expected:  var ret = a - (b + c);

Seems an operator associativity problem within a group of operators with identical precedence. There’s most likely additionnal cases to substraction operator case.

**Comment by uxmal** [comment]
The output stage is not aware of precedence and associativity. I will have a fix for this next week.

**Comment by BrunoGagnon-Eaton** [comment]
Hi! Btw many thanks for your pytocs tool! It really helps me to convert a python 6 000 lines of code written by a power Eng. colleague.  I had to develop my own strategy to include proper data variable/function typing. I also defined a QA strategy to compare results and detailed function calls traces from python Eng. program execution Vs C# execution. With a non-negligible amount of effort, the outcome is a C# program (and results) perfectly aligned with python original program running 3 times faster!. Again many thanks!

**Comment by uxmal** [comment]
Thanks for the kind words Bruno. I happy to hear pytocs is proving useful to you. I will be back at the keyboard in a few days to fix the issues you've reported. If you have ideas and suggestions for enhancements please don't hesitate to open issues for them.
