### ISSUE TITLE
Not able build in VS 2015

### ISSUE THREAD

**Issue by MaheshReddy11** [uxmal/pytocs#18]
Not able build in VS 2015. please let meldow i could be able to build.

![image](https://user-images.githubusercontent.com/34535076/36961494-a8dee26a-2071-11e8-9cfd-3d6b00bf9c21.png)

**Comment by uxmal** [comment]
Pytocs uses language constructs from C# 7.0. Unfortunately VS 2015 doesn't support them. Consider upgrading to VS 2017.
