### ISSUE TITLE
Roadmap Question

### ISSUE THREAD

**Issue by indazoo** [uxmal/pytocs#23]
Hi
First, let me say this project is really well coded and works great!
Still, in the converted project are more than 10'000 errors (according to Visual Studio). One big chunk would be the announced type detection. For me, this seems to be a non-trivial thing to do. Do you have an idea when you will implement it? Is there a beta version or do you have an idea how to implement it? How could we support you?
I don't want to pressure you, just asking.

**Comment by uxmal** [comment]
Thanks for your interest in `pytocs`! You're correct that currently, pytocs does a simple syntactic translation of the Python source code without taking heed of the data types present. 

Given the dynamic nature of the language it's not reasonable to expect the resulting code C# code to be immediately compileable, even with type support. However, for most reasonably Python codebases, the vast majority of the code will have deducible types.

What I've done is ported the https://github.com/leafgray/pysonar2 to the pytocs codebase as a starting point. That work is done. The next step is "assimilating" it as the coding style of the original Java code needs to be adapted to the rest of the pytocs framework. Once that assimilation is done, the result will be Python annotations for all statements, identifiers and constants in the program. It should then be possible for the C# translation pass to take advantage of this. THe C# translation pass will need to take into account nullable ints and the gap between Python callables and the C# equivalent lambda expressions.

As for time schedule, it's harder for me to say as, alas, my work does take priority. I try to make new commits every once in a while. Given enough encouragement I might dedicate more of my spare time to this project -- but https://github.com/uxmal/reko does eat a lot of my time :)

**Comment by uxmal** [comment]
`pytocs` has had type inference for a few weeks now. It's still not 100% awesome, but much better than before. I'm closing this issue now, as I think the core of the question you stated has been addressed. If you find any specific bugs in `pytocs`, please don't hesitate to open new issues.
