### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by agungsugiarto** [uxmal/pytocs#24]
Hello i wanna ask, how to run in visual studio ?

**Comment by uxmal** [comment]
You'll need a version of Visual Studio than can compile C# 7.0. Open the `~/src/pytocs.sln` file and make sure the `pytocs` project is default. You can do this by right-clicking on `pytocs` in the solution explorer and selecting `Set as Startup project`. Then you need to give it command line arguments. This is done by right-clicking on `pytocs` and selecting `Properties`. In the `Properties` view, select the `Debug` tab and make sure that 

* the start action is set to `Start project`
* the command line arguments are either the name of a file:
```
foo.py
```
or the name of a directory; in this case you should use the `-r` option (for `recursive`):
```
-r c:\foo\bar\pythonfiles
```

**Comment by uxmal** [comment]
I assume all has gone well so I'm closing this issue now. If you still have questions, just open a new one.
