### ISSUE TITLE
how to use pytocs

### ISSUE THREAD

**Issue by rituraj17** [uxmal/pytocs#25]
I am new to python and was unable to use your pytocs to convert to c# code can you just specify what we have to do install pytocs or how to use it

**Comment by uxmal** [comment]
pytocs is a command line program. You need to either compile it yourself with Visual Studio, MSBuild, or another appropriate build tool, then use the resulting `pytocs.exe` executable to translate python files (see the README.md file for examples of how to do that).

If you are unable to compile the tool yourself, look for the most recent CI build on [appveyor.com](https://ci.appveyor.com/project/uxmal/pytocs/build/artifacts)
