### ISSUE TITLE
Python J - j complex number notation is generate an exception

### ISSUE THREAD

**Issue by awol2007** [uxmal/pytocs#26]
Hi!

First of all, it is a great project and please do not stop the development. 
Big help for converting from python.
But i can find some exceptions.
I try to convert the following source, and the converter is generating many exceptions.
http://www.scorchworks.com/K40whisperer/K40_Whisperer-0.24_src.zip
The complex numbers 'j' notation and the '1e300000' is an another problem for the converter.

Thanks.

**Comment by uxmal** [comment]
Thanks for the bug report.  This should be fairly simple to fix in the parser. I would probably map these complex numbers to `System.Runtime.Numerics.Complex`

**Comment by uxmal** [comment]
I've fixed the error for `1e3000000` on my machine. The Python lexer was incorrectly parsing it as two separate tokens, `1e30` and `00000`. Now another issue is uncovered: the `1e3000000` will not fit into an IEEE 785 64-bit floating point number by a overwhelming margin. This number is so large that it either requires "BigFloat" support, or should overflow into `System.Double.PositiveInfinity`. What do you think should happen here?

While waiting for your answer, I will work on handling `j`.

**Comment by awol2007** [comment]
Great news. Thanks for the very fast response.
I think, the 1e300000 is a bad habit from the developer. Because in the source checking the infinity value. But the python is very forgiving. :)
This is not my source, i just try to translate to C#.

**Comment by uxmal** [comment]
I've read further and discovered that the `1e300000` was a recommended idiom not too long ago: today you're expected to write `float('+inf')`. I have written logic in `pytocs` to handle this and will be pushing it shortly.

**Comment by uxmal** [comment]
`pytocs` no longer crashes when processing your submitted Python files. I also threw in some more conversion code to handle the Python `complex()` built-in function.
