### ISSUE TITLE
EXPECTED Token type NEWLINE, but saw ID

### ISSUE THREAD

**Issue by Ihavesoul** [uxmal/pytocs#29]
Hi. Thank you for your lib
But i can't use it. I mean, i run my cmd.exe and go to build folder 
And use : 
Pytocs.exe -> foo.py (then i have something like this output)
`
public static class module_name {

    static module_name() {
        foo.py;
    }
}
`
if i use in cmd Pytocs.exe -> pytocs foo.py i have this error :
 System.InvalidOperationException: -(1): Expected token type NEWLINE, but saw ID.

My PY File : 

```
def meshgrid2(*arrs):
    arrs = tuple(reversed(arrs))  #edit
    lens = map(len, arrs)
    dim = len(arrs)

    sz = 1
    for s in lens:
        sz*=s

    ans = []    
    for i, arr in enumerate(arrs):
        slc = [1]*dim
        slc[i] = lens[i]
        arr2 = asarray(arr).reshape(slc)
        for j, sz in enumerate(lens):
            if j!=i:
                arr2 = arr2.repeat(sz, axis=j) 
        ans.append(arr2)

    return tuple(ans)
```

Sorry for bad eng and thank you for attention

**Comment by Ihavesoul** [comment]
Hm... I understand why I have its error 
i should use pytocs -(file_name)
But it's doesn't work
`
public static class module_name {

    static module_name() {
        pytocs - foo.py;
    }
}
`

**Comment by uxmal** [comment]
Strange. When I run `pytocs` on your code I get the following:
```C#
public static class issue29 {

    public static object meshgrid2() {
        var arrs = tuple(reversed(arrs));
        var lens = map(len, arrs);
        var dim = arrs.Count;
        var sz = 1;
        foreach (var s in lens) {
            sz *= s;
        }
        var ans = new List<object>();
        foreach (var _tup_1 in arrs.Select((_p_1,_p_2) => Tuple.Create(_p_2, _p_1))) {
            var i = _tup_1.Item1;
            var arr = _tup_1.Item2;
            var slc = new List<object> {
                1
            } * dim;
            slc[i] = lens[i];
            var arr2 = asarray(arr).reshape(slc);
            foreach (var _tup_2 in lens.Select((_p_3,_p_4) => Tuple.Create(_p_4, _p_3))) {
                var j = _tup_2.Item1;
                sz = _tup_2.Item2;
                if (j != i) {
                    arr2 = arr2.repeat(sz, axis: j);
                }
            }
            ans.append(arr2);
        }
        return tuple(ans);
    }
}
```
The array argument `arrs` is missing from the procedure signature, which I will look into. But otherwise the code looks fine. I ran the command `pytocs issue29.py` to make this happen.

**Comment by uxmal** [comment]
The output now looks OK to me. Are you building `pytocs` yourself or using a released version? The most recent version (which is built after every `git push` to github) is here:
https://ci.appveyor.com/project/uxmal/pytocs/build/artifacts
