### ISSUE TITLE
Comments are lost or misplaced

### ISSUE THREAD

**Issue by uxmal** [uxmal/pytocs#3]
As the current `README.md` shows, the Python comments are not placed in their correct locations.   The sequence
```Python
if foo:
   bar()
# We just called bar
baz()
```
turns into
```C#
if (foo) {
    bar();
    // We just called bar
}
baz();
```
instead of the expected
```C#
if (foo) {
    bar();
}
// We just called bar
baz();
```

**Comment by notzoom** [comment]
Any updates on getting this fixed ? Amazing project btw :)

**Comment by uxmal** [comment]
Thanks for the kind words. I'm working on a fix, but it turns out to be surprisingly awkward to get it implemented correctly. I hope to have some time during the upcoming holiday to work on this and to start introducing real types into the output C# code.

**Comment by uxmal** [comment]
OK, so I pushed hard and got it to work. Enjoy!

**Comment by notzoom** [comment]
Thank you !
