### ISSUE TITLE
Create Avalonia GUI app for pytocs

### ISSUE THREAD

**Issue by SWATOPLUS** [uxmal/pytocs#32]
UI markup sample:

![default](https://user-images.githubusercontent.com/13176763/49081937-68428080-f259-11e8-9b05-1ea3fc9162a1.png)

![default](https://user-images.githubusercontent.com/13176763/49081962-7abcba00-f259-11e8-8790-b19dce8ef262.png)

**Comment by SWATOPLUS** [comment]
Created branch:
https://github.com/SWATOPLUS/pytocs/tree/feature_pytocs-32-create-avalonia-gui-app

**Comment by SWATOPLUS** [comment]
I implemented first version and created PR. https://github.com/uxmal/pytocs/pull/41

**Comment by uxmal** [comment]
The GUI is in place. Now we get to make it nice and shiny. Good work!
