### ISSUE TITLE
Pytocs should recognize and respect Python type annotations

### ISSUE THREAD

**Issue by uxmal** [uxmal/pytocs#33]
Today, Pytocs is confused by Python type annotations like the following:
```
def greeting(name: str) -> str:
     return 'Hello ' + str
```
Pytocs should be able to parse such type annotations and then, during type inference, should use the type annotations directly in the generated code, yielding:
```
public static string greeting(string name) {
     return "Hello " + str;
}
```

**Comment by sairam4123** [comment]
I think this is now fixed.

**Comment by uxmal** [comment]
Indeed, this feature is now implemented.
