### ISSUE TITLE
'-(1): Expected token type NEWLINE, but saw ID.' 

### ISSUE THREAD

**Issue by therollingbird** [uxmal/pytocs#36]
I keep getting this error i just cloed the github solution and nothing is working. tryied to go to https://ci.appveyor.com/project/uxmal/pytocs/build/artifacts and there no artifacts 

please help

![capture](https://user-images.githubusercontent.com/35991749/49146123-973e1c80-f355-11e8-90d8-16cae8b16cf8.PNG)

**Comment by uxmal** [comment]
I'll try to get the build artifacts working again. In the mean time, how are you trying to use `pytocs`? You can convert either a single file:
```
pytocs mypython.py
```
or a directory (and all subdirectories):
```
pytocs -r pythondir
```
If no arguments are specified, it will consume input from stdin.

What does the Python source code look like?

**Comment by uxmal** [comment]
The build artifacts are now generated again. Do let me know if you need any assistance.

**Comment by therollingbird** [comment]
Hi still getting same error even with the artifacts see attached a sample of the python 
and with the source code the file name always returns "-"
[player.zip](https://github.com/uxmal/pytocs/files/2627956/player.zip)

**Comment by uxmal** [comment]
I unpacked the zip file, and -- in a command window -- ran `pytocs -r .` in the directory in which I unzipped the file. I've attached the resulting file. I was unable to see any errors.
[player.py.zip](https://github.com/uxmal/pytocs/files/2628046/player.py.zip)

**Comment by therollingbird** [comment]
![another capture](https://user-images.githubusercontent.com/35991749/49207299-a29e5000-f408-11e8-87cc-2207999603c1.PNG)
here is the result from the artifact maybe im doing something wrong?

**Comment by uxmal** [comment]
That's a different file than the one you sent me: `utils.py` != `player.py`. Could you send me that file also?

**Comment by therollingbird** [comment]
there in the same folder let me send you the folder 
[pydfs_lineup_optimizer.zip](https://github.com/uxmal/pytocs/files/2628320/pydfs_lineup_optimizer.zip)

**Comment by uxmal** [comment]
I was able to run `pytocs -r .` at the root of the folder and all files were translated successfully. 

I'd like to see this fail with my own eyes. Do you use any conferencing software like Skype or TeamViewer we could use? You can contact me on gitter (https://gitter.im/uxmal/pytocs ) to exchange these details privately.

**Comment by uxmal** [comment]
Issue was resolved together with @therollingbird. Same problem as in #29.
