### ISSUE TITLE
Pytocs.Gui: Use *.resx for localization purposes 

### ISSUE THREAD

**Issue by SWATOPLUS** [uxmal/pytocs#42]

**Comment by uxmal** [comment]
I can start on this. Is there any particular language you want to localize to?

**Comment by SWATOPLUS** [comment]
I can transtate it to russian. If you just give me english resx-file.

**Comment by uxmal** [comment]
I've added `Resources.resx` and `Resources.ru.resx` in the `Core` and `Gui` projects. Feel free to add Russian translations at your convenience.

**Comment by karadagi** [comment]
Hi,

I can also add Turkish translation. Could you please add Resources.tr.resx?

**Comment by uxmal** [comment]
@thinklikeanarchitect just copy Resources.resx (which is in English) to Resources.tr.resx and start translating.
