### ISSUE TITLE
Join SciSharp STACK

### ISSUE THREAD

**Issue by Oceania2018** [uxmal/pytocs#49]
Hi CSharp Enthusiasts, 

I think you would be interested in .NET ecosystem in AI. 
Check the [SciSharp STACK](https://github.com/SciSharp). There are several projects needs to convert Python code to CSharp.
It would be great if pytocs could be a member project of SciSharp STACK.

**Comment by uxmal** [comment]
Interesting project. What does "be a member project of SciSharp STACK" entail, exactly?

**Comment by Oceania2018** [comment]
@uxmal Just transfer to `SciSharp STACK` organization, you will still be the owner, and transfer out whenever you want.

**Comment by uxmal** [comment]
How about forking pytocs And adding the fork to your organisation?

**Comment by Oceania2018** [comment]
@uxmal Yes, and I've invited you to the SciSharp STACK architect team.
