### ISSUE TITLE
It doesn't wanna run.

### ISSUE THREAD

**Issue by Dmunch04** [uxmal/pytocs#52]
When I try to run the command, it gives me this error (Sorry it's danish):
```
Ikke-afviklet undtagelse: System.InvalidOperationException: -(1): Expected token type NEWLINE but saw ID.
   ved Pytocs.Core.Syntax.Parser.Error(String str, Object[] args)
   ved Pytocs.Core.Syntax.Parser.Expect(TokenType tokenType)
   ved Pytocs.Core.Syntax.Parser.simple_stmt()
   ved Pytocs.Core.Syntax.Parser.stmt()
   ved Pytocs.Core.Syntax.Parser.<Parse>d__4.MoveNext()
   ved Pytocs.Core.Translate.ModuleTranslator.Translate(IEnumerable`1 statements)
   ved Pytocs.Core.Translator.TranslateModuleStatements(IEnumerable`1 stm, TypeReferenceTranslator types, TextWriter output)
   ved Pytocs.Core.Translator.Translate(String filename, TextReader input, TextWriter output)
   ved Pytocs.Cli.Program.Main(String[] args)
```
What should I do?

Thanks

**Comment by uxmal** [comment]
No problem, jeg førstår dansk ganske vel. How are you launching `pytocs`? The HOWTO.md describes how to start the command line client with the appropriate arguments. If you are starting `pytocs` inside of Visual Studio, you need to make sure the correct command line arguments are specified in the `Debug` tab of the `pytocs` project.

If you still run into problems, contact me on the gitter channel: https://gitter.im/uxmal/pytocs

**Comment by uxmal** [comment]
Closing to do lack of response.
