### ISSUE TITLE
Hmmm... your example on the README.md page does not compile

### ISSUE THREAD

**Issue by CBrauer** [uxmal/pytocs#53]
Is the example on your README.md web page meant to compile with a Microsoft compiler? I put your example in Visual Studio 2017 and it will not compile.  For example:

> 
>         // list comprehension, generating linQ output.
>         public static object apply_map(object mapfn, object filterfn) {
>             return (from n in lst
>                 where filterfn
>                 select mapfn(n)).ToList();
>         }

"lst" is not defined.  There are numerous other errors.  Am I missing something?

Charles

**Comment by uxmal** [comment]
The project is still under development. At this point, the translation is mostly syntactic; Python syntactic elements are translated to C# syntactic elements. Currently underway is an effort to handle type inference properly.  Once this has become stable enough, the README.md will be updated with the improved translation.
