### ISSUE TITLE
Exceptions/Errors construction after translation

### ISSUE THREAD

**Issue by Nucs** [uxmal/pytocs#58]
The following code is a valid python code:
```python
def funcy():
    raise NotImplementedError()
```

should be translated to

``` c#
public void funcy() {
    throw new NotImplementedError();
}
```

Currently it is translated to:
``` c#
public void funcy() {
    throw NotImplementedError();
}
```

Also, `NotImplementedError` should be translated to `NotImplementedException` which is the C# version.

**Comment by uxmal** [comment]
Python's `NotImplementedError` is now translated to `NotImplementedException`.
