### ISSUE TITLE
A Warm Thank You 

### ISSUE THREAD

**Issue by notzoom** [uxmal/pytocs#6]
I had no other way to contact you. 

Thank you for coming up with such a project.

The Python Syntax and Semantics are too powerful to remain to just a handful of interpreted implementations.

If we all work hard on Python Transpilers, we will one day live in a world where things will be much simplified concerning this regard. Keep up the amazing work !

**Comment by uxmal** [comment]
Thanks again for the kind words. I work on pytocs on my spare time, but aim to make it a useful tool. Any ideas you might have or concrete bug reports you could make are of course appreciated.
