### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by michaldengusiak** [uxmal/pytocs#63]
Hi,

I just downloaded the latest version and tried to build solution however I have this error can you please help. Thanks

![image](https://user-images.githubusercontent.com/26113670/70614617-22115280-1c0b-11ea-82a9-4af6dfbec76e.png)

**Comment by uxmal** [comment]
The most recent commits show no errors. I've updated the project to use Avalonia 0.9. There are some major problems with the GUI right now, but the CLI client works fine. I will be gone for another week, but please contact me on the https://gitter.im/uxmal/pytocs channel if you're still having problems.
