### ISSUE TITLE
 support 3.1.3 version of .net core 

### ISSUE THREAD

**Issue by gshields** [uxmal/pytocs#66]
I started out trying the premade binary and then went to doing a git clone and working on a compile. Original I thought I had a problem with the new 3.1.3 core I had installed. After downloading the 4.7.1 developer pack I was was to compile the the Cli and Gui programs.
I converted the nbody.py from computer language shootout, to see how the conversion worked.
I was was to convert the code, but code does not run. I get these errors. 
Program.cs(2,7): error CS0246: The type or namespace name 'sys' could not be found (are you missing a using directive or an assembly reference?) [E:\p-tools\py_src\test\test.csproj]
Program.cs(19,45): error CS0246: The type or namespace name 'list' could not be found (are you missing a using directive or an assembly reference?) [E:\p-tools\py_src\test\test.csproj]
Program.cs(97,53): error CS0246: The type or namespace name 'list' could not be found (are you missing a using directive or an assembly reference?) [E:\p-tools\py_src\test\test.csproj]
Program.cs(138,38): error CS0246: The type or namespace name 'list' could not be found (are you missing a using directive or an assembly reference?) [E:\p-tools\py_src\test\test.csproj]
Program.cs(162,9): error CS0246: The type or namespace name 'list' could not be found (are you missing a using directive or an assembly reference?) [E:\p-tools\py_src\test\test.csproj]
Program.cs(93,19): error CS0246: The type or namespace name 'list' could not be found (are you missing a using directive or an assembly reference?) [E:\p-tools\py_src\test\test.csproj]
Program.cs(97,96): error CS1736: Default parameter value for 'pairs' must be a compile-time constant [E:\p-tools\py_src\test\test.csproj]
Program.cs(138,81): error CS1736: Default parameter value for 'pairs' must be a compile-time constant [E:\p-tools\py_src\test\test.csproj]

I need to Fix the build errors and run again, but do not know enough about redesign python  lists  to c#, so I have some C# learning to do.  Thanks for the program!

**Comment by uxmal** [comment]
The whole project has been moved to `net5.0` -- I hope this will work for you.
