### ISSUE TITLE
Can I use this on my python code that I currently have to embed python on?

### ISSUE THREAD

**Issue by AraHaan** [uxmal/pytocs#7]
I would love to convert this code to C# and drop the python dependency required to run this file in my python embedded interpreters, the main file is located here:

https://github.com/Elskom/Els_kom_new/blob/master/Tools/komformat.py

This would allow me to reduce build time by not:

1. Cloning cpython branch 3.6
2. Building branch 3.6
3. Doing frequent ``git pull`` on branch 3.6 requiring an rebuild of python before building my code.

All of this would greatly reduce not only the compile time I get locally but also in AppVeyor CI.

I am also even debating an plugin system where people can even plug into this and detatch all of the things related to packing and unpacking these from the core, and load them and only invoke them when the file is detected that said plugin *works* for said file. This would even make maintenence time even more easier.

Also does this support python 3.x?

```
1>------ Build started: Project: pytocs, Configuration: Release Any CPU ------
1>E:\Users\Elsword\Desktop\pytocs\src\Translate\StatementTranslator.Tests.cs(1308,7,1308,13): error CS1024: Preprocessor directive expected
1>E:\Users\Elsword\Desktop\pytocs\src\Translate\StatementTranslator.Tests.cs(1332,7,1332,13): error CS1024: Preprocessor directive expected
1>E:\Users\Elsword\Desktop\pytocs\src\Translate\StatementTranslator.Tests.cs(1335,7,1335,14): error CS1024: Preprocessor directive expected
1>E:\Users\Elsword\Desktop\pytocs\src\Translate\StatementTranslator.Tests.cs(1366,3,1366,7): error CS1024: Preprocessor directive expected
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by uxmal** [comment]
Hello and thanks for your interest in pytocs. To answer your question, pytocs _should_ be able to deal with python 3.6 code. I will give it a try on the Python sources you indicated to verify.

However, you need to be aware that pytocs is very much a work in progress. IN particular, the output of the tool doesn't compile yet, as the type inference part is not working correctly yet. What this means is that every translated procedure will have all parameters of type `object` and all return values will be `object`. Naturally I'm working on this, but it means that if you are intending on using pytocs at this early stage, you will have to perform some type analysis yourself.

What I typically do is clone the repository I'm translating, and then create a branch called `pytocs`. I run pytocs on that branch, which generates type-less C#. I then create another branch `cs-port`, where I do my manual work of adding type information. If the original python sources are updated, I go back to `pytocs`, merge the changes, run pytocs.... you get the idea I hope.

I will fix the build error you are seeing shortly, hopefully on the first day of the new year.

**Comment by AraHaan** [comment]
I was able to build it last night only by excluding the file from build in release mode only.

**Comment by uxmal** [comment]
I've fixed the build break you reported and ran pytocs on the Python files you specified. A new feature of Python 3.6 gave the pytocs parser a hiccup, but was also fixed. You should be able to run it on those files now.

**Comment by AraHaan** [comment]
thanks.
