### ISSUE TITLE
Preserve comments and Docstrings.

### ISSUE THREAD

**Issue by sairam4123** [uxmal/pytocs#71]
Current Problem:
    Doesn't preserve the comments and Docstrings
Ideal Solution:
     Preserve those comments and Docstrings, and put it in correct lines.

**Comment by uxmal** [comment]
Could you provide a (small) concrete example of where a particular comment is being lost? Same for docstring: please provide a small concrete example.

**Comment by sairam4123** [comment]
Ok, will do.

**Comment by sairam4123** [comment]
I'm sorry, I'm wrong.
