### ISSUE TITLE
What does @int those here?

### ISSUE THREAD

**Issue by sairam4123** [uxmal/pytocs#72]
I'm really a beginner to C#, converting my python code to C# to save some time, I don't know what does `@int` mean in the below code, and why is that there?
```cs
 public static int hello(int test = @int) 
```
Here's the C# code that was converted:
```cs
public static class test_comment {
    
    //  This is just a test! 
    public static int hello(int test = @int) {
        // return test
        return test;
    }
    
    static test_comment() {
        hello(2);
    }
}
```
The python code that was used to convert into C#.
```py
def hello(test: int) -> int:
    """ This is just a test! """
    # return test
    return test

hello(2)
```
I'm using the latest build from https://ci.appveyor.com/project/uxmal/pytocs/build/artifacts.
Thank you for your response.

**Comment by uxmal** [comment]
That's a bug: the generated C#  should be simply `hello(int test)`.

**Comment by sairam4123** [comment]
Oh, can I just ignore it?

**Comment by uxmal** [comment]
This was fixed yesterday. You shouldn't be seeing these with the latest build of pytocs.

**Comment by sairam4123** [comment]
Oh, ok
