### ISSUE TITLE
The UI crashes on Windows 11 when browsing

### ISSUE THREAD

**Issue by dmihailescu** [uxmal/pytocs#84]
The UI crashes on Windows 11 when browsing for folders.
Only the snippet conversion works in UI, but the C# code
is different from the CLI conversion for class data members.

**Comment by uxmal** [comment]
Can you provide a stack trace of the crash?

**Comment by uxmal** [comment]
Fixed in commit 5273b7054feb299c68ca8adf135524d48ed6b550.
