### ISSUE TITLE
can't build for VS2022 and .net 6

### ISSUE THREAD

**Issue by dmihailescu** [uxmal/pytocs#85]
It might be my lack of knowledge but the CLI and Gui projects can't be upgraded to .net 6 in VS 2022.
I get an error stating:
>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1805,5): error : Project '..\Core\Core.csproj' targets 'net6.0'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v5.0'.
Also I see some third party libraries from Avalonia that can not work well with .net 6

**Comment by uxmal** [comment]
I'll upgrade to .NET 6.0 on my machine to see if I can repro.

**Comment by uxmal** [comment]
I've upgraded all csproj files to .NET 6.0. Remember to do a `dotnet restore` to restore all folders (see commit #91eedff284c9987cf83a547b6946a49fa144a5b7)

**Comment by dmihailescu** [comment]
great thanks!
it works now for GUI too
