### ISSUE TITLE
parser error Expected token type NEWLINE but saw ID.

### ISSUE THREAD

**Issue by ATECoder** [uxmal/pytocs#89]
Here are the relevant lines from pytocs:

```
Error: (C:\pub\lxi\python-vxi11-server-pytocs\vxi11_server\instrument_device.py,90): parser error. Please report on https://github.com/uxmal/pytocs
 C:\pub\lxi\python-vxi11-server-pytocs\vxi11_server\instrument_device.py(90): Expected token type NEWLINE but saw ID.
```
The relevant file is located here:
https://github.com/coburnw/python-vxi11-server/blob/master/vxi11_server/instrument_device.py

**Comment by uxmal** [comment]
You found a bug in Pytocs' Python parser. Thanks for reporting this! It's been fixed in commit bb486f50a199a29b6adddc65a0868fce706cd8ca.
