### ISSUE TITLE
parser error.    Expected token type NEWLINE but saw AT.

### ISSUE THREAD

**Issue by toolgood** [uxmal/pytocs#96]
url: https://github.com/thuml/Transfer-Learning-Library
layers\MultiWaveletCorrelation.py(262): Expected token type NEWLINE but saw AT.

code line 262
``` py
   H0r = H0 @ PHI0  
```

**Comment by uxmal** [comment]
C# doesn't have a built-in matrix multiplication operator `__matmul__`. Pytocs could translate the statement above to:
```C#
H0r = @__matmul__(H0, PHI0);
```
Or, if the command line switch `--intrinsic-matmul` is specifieid, it could translate to:
```C#
H0r = H0 * PHI0;
```
Will this work for you?

**Comment by uxmal** [comment]
Commit a7aaf560f888544bc75d64ad9b472740ee98ee79 implements the logic above, with the exception that the syntax is:
```C#
H0r = H0.@__matmul__(PHI0)
```
Let me know if you need post-processor support for this.
